In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import csv
import datetime as dt
import json

In [24]:
pd.set_option('display.max_columns', None)

In [2]:
steam_df = pd.read_csv('C:/Users/Barbie/Desktop/DA11/Capstone/STEAM/COOKED_STEAM_DATA/games_features_CLEANED.csv')

In [3]:
steam_df = steam_df.drop(columns = ['QueryName'])
steam_df = steam_df.rename(columns = {'ResponseName' : 'Name'})
steam_df.head(3)

,QueryID,ResponseID,Name,ReleaseDate,ReleaseYear,ReleaseMonth,RequiredAge,DLCCount,Metacritic,RecommendationCount,...,GenreIsFreeToPlay,GenreIsSports,GenreIsRacing,GenreIsMassivelyMultiplayer,PriceCurrency,PriceInitial,PriceFinal,AboutText,DetailedDescrip,SupportedLanguages
0,10.0,10.0,Counter-Strike,2000-11-01,2000,November,0,0,88,68991,...,False,False,False,False,USD,9.99,9.99,Play the worlds number 1 online action game. E...,Play the worlds number 1 online action game. E...,English French German Italian Spanish Simplifi...
1,20.0,20.0,Team Fortress Classic,1999-04-01,1999,April,0,0,0,2439,...,False,False,False,False,USD,4.99,4.99,One of the most popular online action games of...,One of the most popular online action games of...,English French German Italian Spanish
2,30.0,30.0,Day of Defeat,2003-05-01,2003,May,0,0,79,2319,...,False,False,False,False,USD,4.99,4.99,Enlist in an intense brand of Axis vs. Allied ...,Enlist in an intense brand of Axis vs. Allied ...,English French German Italian Spanish

In [5]:
steam_df['Name'].value_counts()  # checking for duplicates

Name
Counter-Strike                              1
1943 Megami Strike                          1
The Brookhaven Experiment                   1
Niche - a genetics survival game            1
Mesel                                       1
                                           ..
Cavern Kings                                1
Rising Angels: Reborn                       1
Disney Infinity 2.0: Marvel Super Heroes    1
Silence of the Sleep                        1
Ghostlight Manor                            1
Name: count, Length: 13194, dtype: int64

In [7]:
steam_df.value_counts('ReleaseYear').sort_values().reset_index()  # gives us the unique years and count of releases each year

   ReleaseYear  count
0         1997      1
1         1998      1
2         2019      1
3         1999      2
4         2000      2
5         2003      3
6         2001      4
7         2024      6
8         2005      6
9         2004      8
10        2017     60
11        2006     79
12        2007    117
13        2008    187
14        2011    305
15        2010    314
16        2009    370
17        2012    392
18        2013    550
19        none    857
20        2014   1744
21        2015   3006
22        2016   5342

In [8]:
steam_df.value_counts('ReleaseMonth').reset_index() # gives us the unique months and count of releases each month

   ReleaseMonth  count
0        August   1560
1     September   1287
2       October   1258
3          July   1167
4      November   1081
5          June   1054
6           May   1043
7         April   1008
8         March    882
9          none    857
10     December    791
11     February    726
12      January    643

In [9]:
steam_df.value_counts('RequiredAge').reset_index()  # gives us the unique required ages with how many games were associated

    RequiredAge  count
0             0  12671
1            17    450
2            13     82
3            18     80
4            16     40
5            12     10
6            10      9
7            15      9
8             6      2
9            14      2
10            1      1
11            7      1

In [10]:
steam_df['Metacritic'].reset_index().sort_values('Metacritic', ascending = False) #gives us all games with Metacritic ratings

       index  Metacritic
10        10          96
6          6          96
3088    3088          96
232      232          96
26        26          95
...      ...         ...
5711    5711           0
5712    5712           0
5713    5713           0
5715    5715           0
13356  13356           0

[13357 rows x 2 columns]

In [11]:
all_steam_data_MERGED = pd.read_json(r"C:\Users\Barbie\Desktop\DA11\Capstone\STEAM\API_CALLS_STEAM\COMBINED_TESTING_2.json")

all_steam_data_MERGED

# this is 73 seperate json files from 73 API Steam calls that I merged into one large json file using Notepad ++

,570,730,578080,1063730,1623730,1172470,440,1938090,271590,550,...,2575100,2917700,2500080,2443520,2216600,1963990,1726330,740310,1285350,789930
appid,570,730,578080,1063730,1623730,1172470,440,1938090,271590,550,...,2575100,2917700,2500080,2443520,2216600,1963990,1726330,740310,1285350,789930
name,Dota 2,Counter-Strike: Global Offensive,PUBG: BATTLEGROUNDS,New World,Palworld,Apex Legends,Team Fortress 2,Call of Duty: Modern Warfare II,Grand Theft Auto V,Left 4 Dead 2,...,V-Monsters Digital Farm,Buggy Derby Arena,Webventure,Purrfect Rescue,Korea Dynasty (조선메타실록),Deliver Us From Evil (DUFE) - Masquerade,Game Developer Simulator,Transmogrify,Easy puzzle: Landscape,Blind Boris
developer,Valve,Valve,"KRAFTON, Inc.",Amazon Games,Pocketpair,Respawn,Valve,"Sledgehammer Games, Treyarch, Infinity Ward, B...",Rockstar North,Valve,...,Red Studios,bam14,Moodming,Gray Boss,Happy Daram Inc.,Galen Games,Phantom Studio,Odyssey Entertainment,Laush Dmitriy Sergeevich,Marginal act
publisher,Valve,Valve,"KRAFTON, Inc.",Amazon Games,Pocketpair,Electronic Arts,Valve,Activision,Rockstar Games,Valve,...,GoGo Games Interactive,bam14,Moodming,Gray Boss,Happy Daram Inc.,Galen Games,Phantom Studio,Odyssey Entertainment,Laush Studio,Marginal act
score_rank,,,,,,,,,,,...,,,,,,,,,,
positive,1836663,7034475,1380986,193004,280252,645151,980557,333373,1557234,834854,...,8,12,18,32,128,4,3,21,12,11
negative,408414,1032480,981812,81497,18423,183785,66218,240280,236827,21169,...,1,1,29,3,66,2,7,2,2,13
userscore,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
owners,"100,000,000 .. 200,000,000","100,000,000 .. 200,000,000","50,000,000 .. 100,000,000","50,000,000 .. 100,000,000","50,000,000 .. 100,000,000","50,000,000 .. 100,000,000","50,000,000 .. 100,000,000","50,000,000 .. 100,000,000","50,000,000 .. 100,000,000","50,000,000 .. 100,000,000",...,"0 .. 20,000","0 .. 20,000","0 .. 20,000","0 .. 20,000","0 .. 20,000","0 .. 20,000","0 .. 20,000","0 .. 20,000","0 .. 20,000","0 .. 20,000"
average_forever,56164,34060,23979,11793,2634,12032,8230,3299,12490,3037,...,0,0,0,0,0,0,0,0,0,35
average_2weeks,2477,593,1028,353,742,1042,1756,343,598,187,...,0,0,0,0,0,0,0,0,0,0
median_forever,971,8390,10192,10422,2143,2149,890,354,6495,827,...,0,0,0,0,0,0,0,0,0,35
median_2weeks,2060,286,751,445,238,376,309,80,253,78,...,0,0,0,0,0,0,0,0,0,0
price,0,0,0,3999,2999,0,0,6999,2998,999,...,399,1999,799,199,1999,499,399,1499,399,1299
initialprice,0,0,0,3999,2999,0,0,6999,2998,999,...,499,1999,799,199,1999,499,399,1499,399,1299
discount,0,0,0,0,0,0,0,0,0,0,...,20,0,0,0,0,0,0,0,0,0
ccu,851269,1242112,396605,7073,22622,219745,98632,81889,135799,25564,...,0,0,0,5,2,0,0,0,0,0

In [12]:
all_steam_data = all_steam_data_MERGED.transpose()  
all_steam_data     # using this to turn the columns into rows and the rows into columns

all_steam_data = all_steam_data.rename(
    columns = {'appid' : 'App_Id',
               'name' : 'Name',
               'developer' : 'Developer',
               'publisher' : 'Publisher',
               'score_rank' : 'Score_Rank',
               'positive' : 'Postive_Reviews',
               'negative' : 'Negative_Reviews',
               'userscore' : 'Userscore',
               'owners' : 'Owners',
               'average_forever' : 'Avg_Playtime_Lifetime',
               'average_2weeks' : 'Avg_Playtime_Two_Weeks',
               'median_forever' : 'Median_Playtime_Lifetime',
               'median_2weeks' : 'Median_Playtime_Two_Weeks',
               'price' : 'Current_Price',
               'initialprice' : 'Initial_Price',
               'discount' : 'Discount',
               'ccu' : 'Peak_CCU'})
all_steam_data     # renaming all the columns to make it flow better

all_steam_data = all_steam_data.reset_index()
all_steam_data     # resetting the index since it seemed to have its own index column identical to the "App_id" column

all_steam_data = all_steam_data.drop(columns = ['index'])
all_steam_data     # dropped the other index column to have the tradiation index column to run alongside the "App_id" column

,App_Id,Name,Developer,Publisher,Score_Rank,Postive_Reviews,Negative_Reviews,Userscore,Owners,Avg_Playtime_Lifetime,Avg_Playtime_Two_Weeks,Median_Playtime_Lifetime,Median_Playtime_Two_Weeks,Current_Price,Initial_Price,Discount,Peak_CCU
0,570,Dota 2,Valve,Valve,,1836663,408414,0,"100,000,000 .. 200,000,000",56164,2477,971,2060,0,0,0,851269
1,730,Counter-Strike: Global Offensive,Valve,Valve,,7034475,1032480,0,"100,000,000 .. 200,000,000",34060,593,8390,286,0,0,0,1242112
2,578080,PUBG: BATTLEGROUNDS,"KRAFTON, Inc.","KRAFTON, Inc.",,1380986,981812,0,"50,000,000 .. 100,000,000",23979,1028,10192,751,0,0,0,396605
3,1063730,New World,Amazon Games,Amazon Games,,193004,81497,0,"50,000,000 .. 100,000,000",11793,353,10422,445,3999,3999,0,7073
4,1623730,Palworld,Pocketpair,Pocketpair,,280252,18423,0,"50,000,000 .. 100,000,000",2634,742,2143,238,2999,2999,0,22622
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70773,1963990,Deliver Us From Evil (DUFE) - Masquerade,Galen Games,Galen Games,,4,2,0,"0 .. 20,000",0,0,0,0,499,499,0,0
70774,1726330,Game Developer Simulator,Phantom Studio,Phantom Studio,,3,7,0,"0 .. 20,000",0,0,0,0,399,399,0,0
70775,740310,Transmogrify,Odyssey Entertainment,Odyssey Entertainment,,21,2,0,"0 .. 20,000",0,0,0,0,1499,1499,0,0
70776,1285350,Easy puzzle: Landscape,Laush Dmitriy Sergeevich,Laush Studio,,12,2,0,"0 .. 20,000",0,0,0,0,399,399,0,0
70777,789930,Blind Boris,Marginal act,Marginal act,,11,13,0,"0 .. 20,000",35,0,35,0,1299,1299,0,0

In [13]:
# from pathlib import Path  
# filepath = Path(r'C:\Users\Barbie\Desktop\DA11\Capstone\STEAM\COOKED_STEAM_DATA\all_steam_data.csv')  
# filepath.parent.mkdir(parents=True, exist_ok=True)  
# all_steam_data.to_csv(filepath)  

# imported it out as a csv to load into Excel
# commented it out so it doesn't create a new csv every time I run the notebook :)

In [14]:
all_steam_data.duplicated(subset = ['Name']).value_counts()

False    70330
True       448
Name: count, dtype: int64

In [15]:
#dropping duplicate game names

all_steam_data = all_steam_data.drop_duplicates(subset = ['Name'], keep = 'last')
all_steam_data

,App_Id,Name,Developer,Publisher,Score_Rank,Postive_Reviews,Negative_Reviews,Userscore,Owners,Avg_Playtime_Lifetime,Avg_Playtime_Two_Weeks,Median_Playtime_Lifetime,Median_Playtime_Two_Weeks,Current_Price,Initial_Price,Discount,Peak_CCU
0,570,Dota 2,Valve,Valve,,1836663,408414,0,"100,000,000 .. 200,000,000",56164,2477,971,2060,0,0,0,851269
1,730,Counter-Strike: Global Offensive,Valve,Valve,,7034475,1032480,0,"100,000,000 .. 200,000,000",34060,593,8390,286,0,0,0,1242112
2,578080,PUBG: BATTLEGROUNDS,"KRAFTON, Inc.","KRAFTON, Inc.",,1380986,981812,0,"50,000,000 .. 100,000,000",23979,1028,10192,751,0,0,0,396605
3,1063730,New World,Amazon Games,Amazon Games,,193004,81497,0,"50,000,000 .. 100,000,000",11793,353,10422,445,3999,3999,0,7073
4,1623730,Palworld,Pocketpair,Pocketpair,,280252,18423,0,"50,000,000 .. 100,000,000",2634,742,2143,238,2999,2999,0,22622
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70773,1963990,Deliver Us From Evil (DUFE) - Masquerade,Galen Games,Galen Games,,4,2,0,"0 .. 20,000",0,0,0,0,499,499,0,0
70774,1726330,Game Developer Simulator,Phantom Studio,Phantom Studio,,3,7,0,"0 .. 20,000",0,0,0,0,399,399,0,0
70775,740310,Transmogrify,Odyssey Entertainment,Odyssey Entertainment,,21,2,0,"0 .. 20,000",0,0,0,0,1499,1499,0,0
70776,1285350,Easy puzzle: Landscape,Laush Dmitriy Sergeevich,Laush Studio,,12,2,0,"0 .. 20,000",0,0,0,0,399,399,0,0
70777,789930,Blind Boris,Marginal act,Marginal act,,11,13,0,"0 .. 20,000",35,0,35,0,1299,1299,0,0

In [16]:
# steam_merged = steam_df.append(all_steam_data, ignore_index = True)

In [17]:
# steam_merged = pd.concat([steam_df, all_steam_data], ignore_index = False, sort = False)

In [18]:
# steam_merged

In [19]:
# steam_merged.info()

In [25]:
steam_merged = steam_df.merge(all_steam_data, on = 'Name', how = 'outer')

In [26]:
steam_merged    # left off HERE! Need to move some columns around and rename a few to get it looking better

,QueryID,ResponseID,Name,ReleaseDate,ReleaseYear,ReleaseMonth,RequiredAge,DLCCount,Metacritic,RecommendationCount,ScreenshotCount,SteamSpyOwners,SteamSpyPlayersEstimate,AchievementCount,ControllerSupport,IsFree,SubscriptionAvail,PlatformWindows,PlatformLinux,PlatformMac,CategorySinglePlayer,CategoryMultiplayer,CategoryCoop,CategoryMMO,CategoryInAppPurchase,CategoryVRSupport,GenreIsNonGame,GenreIsIndie,GenreIsAction,GenreIsAdventure,GenreIsCasual,GenreIsStrategy,GenreIsRPG,GenreIsSimulation,GenreIsEarlyAccess,GenreIsFreeToPlay,GenreIsSports,GenreIsRacing,GenreIsMassivelyMultiplayer,PriceCurrency,PriceInitial,PriceFinal,AboutText,DetailedDescrip,SupportedLanguages,App_Id,Developer,Publisher,Score_Rank,Postive_Reviews,Negative_Reviews,Userscore,Owners,Avg_Playtime_Lifetime,Avg_Playtime_Two_Weeks,Median_Playtime_Lifetime,Median_Playtime_Two_Weeks,Current_Price,Initial_Price,Discount,Peak_CCU
0,10.0,10.0,Counter-Strike,2000-11-01,2000,November,0.0,0.0,88.0,68991.0,13.0,13033334.0,9140731.0,0.0,False,False,False,True,True,True,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,9.99,9.99,Play the worlds number 1 online action game. E...,Play the worlds number 1 online action game. E...,English French German Italian Spanish Simplifi...,10,Valve,Valve,,231059,6030,0,"10,000,000 .. 20,000,000",20071,424,24333,378,999,999,0,12918
1,20.0,20.0,Team Fortress Classic,1999-04-01,1999,April,0.0,0.0,0.0,2439.0,5.0,5399140.0,753627.0,0.0,False,False,False,True,True,True,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,4.99,4.99,One of the most popular online action games of...,One of the most popular online action games of...,English French German Italian Spanish,20,Valve,Valve,,7078,1070,0,"5,000,000 .. 10,000,000",117,0,57,0,499,499,0,81
2,30.0,30.0,Day of Defeat,2003-05-01,2003,May,0.0,0.0,79.0,2319.0,5.0,7621102.0,1709740.0,0.0,False,False,False,True,True,True,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,4.99,4.99,Enlist in an intense brand of Axis vs. Allied ...,Enlist in an intense brand of Axis vs. Allied ...,English French German Italian Spanish,30,Valve,Valve,,6102,666,0,"5,000,000 .. 10,000,000",549,0,25,0,499,499,0,125
3,40.0,40.0,Deathmatch Classic,2001-06-01,2001,June,0.0,0.0,0.0,888.0,4.0,7498965.0,789676.0,0.0,False,False,False,True,True,True,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,4.99,4.99,Enjoy fast-paced multiplayer gaming with Death...,Enjoy fast-paced multiplayer gaming with Death...,English French German Italian Spanish,40,Valve,Valve,,2438,514,0,"5,000,000 .. 10,000,000",706,0,4,0,499,499,0,5
4,50.0,50.0,Half-Life: Opposing Force,1999-11-01,1999,November,0.0,0.0,0.0,2934.0,5.0,5399499.0,705741.0,0.0,False,False,False,True,True,True,True,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,4.99,4.99,Return to the Black Mesa Research Facility as ...,Return to the Black Mesa Research Facility as ...,English French German Korean,50,Gearbox Software,Valve,,21083,1068,0,"2,000,000 .. 5,000,000",2631,5,2378,5,499,499,0,106
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74198,NaN,NaN,Deliver Us From Evil (DUFE) - Masquerade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1963990,Galen Games,Galen Games,,4,2,0,"0 .. 20,000",0,0,0,0,499,499,0,0
74199,NaN,NaN,Game Developer Simulator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1726330,Phantom Studio,Phantom Studio,,3,7,0,"0 .. 20,000",0,0,0,0,399,399,0,0
74200,NaN,NaN,Transmogrify,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,740310,Odyssey Entertainment,Odyssey Entertainment,,21,2,0,"0 .. 20,000",0,0,0,0,1499,1499,0,0
74201,NaN,NaN,Easy puzzle: Landscape,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1285350,Laush Dmitriy Sergeevich,Laush Studio,,12,2,0,"0 .. 20,000",0,0,0,0,399,399,0,0
74202,NaN,NaN,Blind Boris,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,789930,Marginal act,Marginal act,,11,13,0,"0 .. 20,000",35,0,35,0,1299,1299,0,0

In [27]:
steam_df[steam_df['Name'] == 'Blind Boris']

Empty DataFrame
Columns: [QueryID, ResponseID, Name, ReleaseDate, ReleaseYear, ReleaseMonth, RequiredAge, DLCCount, Metacritic, RecommendationCount, ScreenshotCount, SteamSpyOwners, SteamSpyPlayersEstimate, AchievementCount, ControllerSupport, IsFree, SubscriptionAvail, PlatformWindows, PlatformLinux, PlatformMac, CategorySinglePlayer, CategoryMultiplayer, CategoryCoop, CategoryMMO, CategoryInAppPurchase, CategoryVRSupport, GenreIsNonGame, GenreIsIndie, GenreIsAction, GenreIsAdventure, GenreIsCasual, GenreIsStrategy, GenreIsRPG, GenreIsSimulation, GenreIsEarlyAccess, GenreIsFreeToPlay, GenreIsSports, GenreIsRacing, GenreIsMassivelyMultiplayer, PriceCurrency, PriceInitial, PriceFinal, AboutText, DetailedDescrip, SupportedLanguages]
Index: []

In [28]:
all_steam_data[all_steam_data['Name'] == 'Blind Boris']

,App_Id,Name,Developer,Publisher,Score_Rank,Postive_Reviews,Negative_Reviews,Userscore,Owners,Avg_Playtime_Lifetime,Avg_Playtime_Two_Weeks,Median_Playtime_Lifetime,Median_Playtime_Two_Weeks,Current_Price,Initial_Price,Discount,Peak_CCU
70777,789930,Blind Boris,Marginal act,Marginal act,,11,13,0,"0 .. 20,000",35,0,35,0,1299,1299,0,0

In [29]:
steam_merged[steam_merged['Name'] == 'Blind Boris']

,QueryID,ResponseID,Name,ReleaseDate,ReleaseYear,ReleaseMonth,RequiredAge,DLCCount,Metacritic,RecommendationCount,ScreenshotCount,SteamSpyOwners,SteamSpyPlayersEstimate,AchievementCount,ControllerSupport,IsFree,SubscriptionAvail,PlatformWindows,PlatformLinux,PlatformMac,CategorySinglePlayer,CategoryMultiplayer,CategoryCoop,CategoryMMO,CategoryInAppPurchase,CategoryVRSupport,GenreIsNonGame,GenreIsIndie,GenreIsAction,GenreIsAdventure,GenreIsCasual,GenreIsStrategy,GenreIsRPG,GenreIsSimulation,GenreIsEarlyAccess,GenreIsFreeToPlay,GenreIsSports,GenreIsRacing,GenreIsMassivelyMultiplayer,PriceCurrency,PriceInitial,PriceFinal,AboutText,DetailedDescrip,SupportedLanguages,App_Id,Developer,Publisher,Score_Rank,Postive_Reviews,Negative_Reviews,Userscore,Owners,Avg_Playtime_Lifetime,Avg_Playtime_Two_Weeks,Median_Playtime_Lifetime,Median_Playtime_Two_Weeks,Current_Price,Initial_Price,Discount,Peak_CCU
74202,NaN,NaN,Blind Boris,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,789930,Marginal act,Marginal act,,11,13,0,"0 .. 20,000",35,0,35,0,1299,1299,0,0

# Question 1:

# How many games offer both keyboard and controller support? Are there different genres of games that seem to support more of one than the other?